name: carauction
services:

  processor:
    container_name: processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5021;http://+:5020
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "5020:5020"
      - "5021:5021"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  webapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  reporting-webapi:
    container_name: reporting-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;http://+:6000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  keycloak:
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: auctionadmin
      KC_DB_PASSWORD: auctionadmin
      KC_HOSTNAME: localhost
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - ./.containers/keycloak:/opt/keycloak/data

  jaeger:
    container_name: jaeger
    ports:
    - "16686:16686"
    - "4317:4317" 
    - "4318:4318" 

  postgres:
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: auctionadmin
      POSTGRES_PASSWORD: auctionadmin
      POSTGRES_DB: carauction
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres-app:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
     - ./.containers/rabbitmq/data:/var/lib/rabbitmq
     - ./.containers/rabbitmq/log:/var/log/rabbitmq
