services:

  carauctionapp-processor:
    container_name: carauctionapp-processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5021;http://+:5020
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://carauctionapp-jaeger:4317
    depends_on:
      carauctionapp-postgres:
        condition: service_started
      carauctionapp-rabbitmq:
        condition: service_started
    ports:
      - "5020:5020"
      - "5021:5021"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  carauctionapp-webapi:
    container_name: carauctionapp-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://carauctionapp-jaeger:4317
    depends_on:
      carauctionapp-postgres:
        condition: service_started
      carauctionapp-rabbitmq:
        condition: service_started
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  carauctionapp-reporting-webapi:
    container_name: carauctionapp-reporting-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;http://+:6000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://carauctionapp-jaeger:4317
    depends_on:
      carauctionapp-postgres:
        condition: service_started
      carauctionapp-rabbitmq:
        condition: service_started
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  carauctionapp-postgres:
    container_name: carauctionapp-postgres
    environment:
      POSTGRES_USER: auctionadmin
      POSTGRES_PASSWORD: auctionadmin
      POSTGRES_DB: carauction
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres-app:/var/lib/postgresql/data

  carauctionapp-reporting-postgres:
    container_name: carauctionapp-reporting-postgres
    environment:
      POSTGRES_USER: auctionadmin
      POSTGRES_PASSWORD: auctionadmin
      POSTGRES_DB: carauctionreporting
    ports:
      - "5433:5433"
    volumes:
      - ./.containers/postgres-reporting:/var/lib/postgresql/data

  carauctionapp-rabbitmq:
    container_name: carauctionapp-rabbitmq
    hostname: carauctionapp-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
     - ./.containers/rabbitmq/data:/var/lib/rabbitmq
     - ./.containers/rabbitmq/log:/var/log/rabbitmq

  carauctionapp-jaeger:
    container_name: carauctionapp-jaeger
    ports:
    - "16686:16686"
    - "4317:4317" 
    - "4318:4318" 
