name: carauction
services:
  processor:
    image: ${DOCKER_REGISTRY-}processor
    build:
      context: .
      dockerfile: ../app/CarAuctionApp.Processor/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ../app/CarAuctionApp.WebApi/Dockerfile

  reporting-webapi:
    image: ${DOCKER_REGISTRY-}reportingwebapi
    build:
      context: .
      dockerfile: ../reporting/CarAuctionApp.Reporting.WebApi/Dockerfile

  postgres:
    image: postgres:17

  rabbitmq:
    image: rabbitmq:4-management

  jaeger:
    image: jaegertracing/all-in-one:latest

  keycloak:
      image: quay.io/keycloak/keycloak:latest

