services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: auctionadmin
      POSTGRES_PASSWORD: auctionadmin
      POSTGRES_DB: carauction
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    networks:
      - carauction_network

networks:
  carauction_network:
    driver: bridge
