name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore CarAuctionApp.sln
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore CarAuctionApp.sln
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity normal CarAuctionApp.sln
        working-directory: ./src

  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci
        working-directory: ./src/carauctionapp-auctionsite

      - name: Run Linter
        run: npm run lint
        working-directory: ./src/carauctionapp-auctionsite

      - name: Build React Project
        run: npm run build
        working-directory: ./src/carauctionapp-auctionsite
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black mypy pytest pytest-cov pip-audit

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 ./src/ai/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check formatting with black
        run: |
          source venv/bin/activate
          black --check ./src/ai/

      - name: Type check with mypy
        run: |
          source venv/bin/activate
          mypy ./src/ai/

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --cov=./src/ai/ --cov-report=xml

      - name: Run pip-audit
        run: |
          source venv/bin/activate
          pip-audit
