name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore CarAuctionApp.sln
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore CarAuctionApp.sln
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity normal CarAuctionApp.sln
        working-directory: ./src

  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci
        working-directory: ./src/carauctionapp-auctionsite

      - name: Run Linter
        run: npm run lint
        working-directory: ./src/carauctionapp-auctionsite

      - name: Build React Project
        run: npm run build
        working-directory: ./src/carauctionapp-auctionsite

      - name: Run Tests
        run: npm test -- --watchAll=false
        working-directory: ./src/carauctionapp-auctionsite
