name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore CarAuctionApp.sln
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore CarAuctionApp.sln
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity normal CarAuctionApp.sln
        working-directory: ./src

  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci
        working-directory: ./src/carauctionapp-auctionsite

      - name: Run Linter
        run: npm run lint
        working-directory: ./src/carauctionapp-auctionsite

      - name: Build React Project
        run: npm run build
        working-directory: ./src/carauctionapp-auctionsite

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black myp
        working-directory: ./src/ai

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        working-directory: ./src/ai

      - name: Check formatting with black
        run: |
          source venv/bin/activate
          black --check .
        working-directory: ./src/ai

      - name: Type check with mypy
        run: |
          source venv/bin/activate
          mypy .
        working-directory: ./src/ai
